### ISSUE TITLE
fakeEvent implicitly called value subscriber is missing its value

### ISSUE THREAD

**Issue by TiraO** [soumak77/firebase-mock#22]
When I add a `value` subscriber to a new child when it is added, firebase-mock immediately calls the subscriber (as it should), but without the value set in the ref passed to the subscriber.
Real firebase calls the subscriber with the value set.

Here is a jasmine test that shows this behavior: 

```javascript
describe("adding a child", () => {
  let ref;
  beforeEach(() => {
    ref = firebase.database().ref('/some-ref').push();
  });

  describe("when subscribing to newly added values", ()=> {
    let valueCallbackSpy;

    beforeEach(() => {
      valueCallbackSpy = jasmine.createSpy('valueCallbackSpy');

      ref.on('child_added', function (snapshot) {
        snapshot.ref.on('value', valueCallbackSpy);
      });
    });

    it("calls the value subscriber", ()=> {
      ref.fakeEvent('child_added', 'some-key', 'some-value', '');
      ref.flush();

      expect(valueCallbackSpy).toHaveBeenCalled();
    });

    it("passes a key and value to the subscriber", ()=> {
      ref.fakeEvent('child_added', 'some-key', 'some-value', '');
      ref.flush();
      let snapshot = valueCallbackSpy.calls.argsFor(0)[0];
      expect(snapshot.key).toEqual('some-key');
      expect(snapshot.val()).toEqual('some-value'); // ** this line fails because val() is null **
    });
  });
});
```

Alternatively if triggering the fake child_added event didn't call the value subscriber at all, I think that would be okay. One could call that manually as a separate fake event. It's kind of strange that the 'value' event gets queued up and called within the same flush action.

**Comment by soumak77** [comment]
@TiraO after trying to debug the code, I've come to the conclusion that this functionality appears to be by design.  Using a `fakeEvent` does not modify the values in the database.  Therefore calling `snapshot.ref` inside the `child_added` handler will give you a reference to the database without the value added by the `fakeEvent`.

Therefore to get the functionality you have in the test, you will need to `set` the value in the database which will trigger the `child_added` event.
