### ISSUE TITLE
Running MockFirebase under Web Worker

### ISSUE THREAD

**Issue by dulimarta** [soumak77/firebase-mock#26]
In the last several days I did extensive research to solve an issue running MockFirebase under a Web Worker. After reading [Issue 131](https://github.com/lodash/lodash/issues/313) of Lodash, I noticed that included under `firebase-mock/node_modules` is Lodash 2.x.

My quick fix is to rename `firebase-mock/node-modules` so it is excluded from normal Node search path, forcing a newer version of Lodash 3.x included in my build.

**Comment by soumak77** [comment]
@dulimarta can you submit a PR with lodash upgraded to 3.x?  Assuming the test cases pass, I'll merge it and publish a new release

**Comment by soumak77** [comment]
@dulimarta if you could add a test case demoing the issue that would be great as well, though I'm not sure how difficult it is to test a Web Worker

**Comment by dulimarta** [comment]
@soumak77 would it be possible to create two MockFirebase instances (one under the main thread and another under a web worker thread) that refer to the **same data**. From I'm able to do so far, the two instances I created in my experiment did not seem to share a common data.

**Comment by soumak77** [comment]
@dulimarta That won't be possible since both instances will write to their own memory cache.  Instead you could design the web worker to support dependency injection and pass an instance of the firebase app to the web worker instead of the web worker creating the firebase instance.

If this method doesn't work, you might want to consider another library for testing your web worker.  You can use [firebase-server](https://github.com/urish/firebase-server) as an alternative.  This should allow you to create multiple instances of firebase which all connect to the same datastore.  I use firebase-server when needing to write any non-unit test cases for my firebase code.

You can check out https://github.com/greenhousegames/firebase-reporting for an example on how to use firebase-server for testing (specifically https://github.com/greenhousegames/firebase-reporting/blob/master/test/helpers.js)

**Comment by dulimarta** [comment]
Thanks for your feedback on more web worker details, firebase-server, and firebase-reporting.

BTW, I have a new branch lodash-3 that upgrades Lodash to 3.10.1. I had to make minor changes in `firebase.js` and `query.js` to pass 3 failing tests.

I should probably create a new PR before adding test cases for web worker.

**Comment by soumak77** [comment]
@dulimarta were you able to get this library working for a web worker?

**Comment by soumak77** [comment]
Closing this issue as will not fix.  Use [firebase-server](https://github.com/urish/firebase-server) for testing with web workers.
