### ISSUE TITLE
Add suport for order queries

### ISSUE THREAD

**Issue by posva** [soumak77/firebase-mock#4]
Hi, great job on the mock working very nice so far 😄 
Order queries like `someRef.orderByChild('index')` are not supported. Do you plan to support them?

**Comment by soumak77** [comment]
I don't plan on making any changes immediately myself, but I will accept PRs.  The problem is that ordering can get quiet complex, so mocking this behavior may lead to inconsistencies between how the actual firebase library does ordering vs the mock.  So long as your use case is simple then mocking the ordering behavior should work fine.

If you have a more complex use case that is difficult to mock, the suggestion would be move that unit test to an integration/e2e test and use [firebase-server](https://github.com/urish/firebase-server) for testing.

**Comment by Caerbannog** [comment]
Note that some work has been done in the base repository:
https://github.com/katowulf/mockfirebase/pull/61

**Comment by posva** [comment]
@Caerbannog Unfortunately that project is abandoned 😞

**Comment by alfonsodev** [comment]
@posva but would you like that the mock is smart to order your data ? 
or just the ability to set what that function should return in case by case basis ? 

For example having an auxiliary method `firebaseMock.__setOrderByChild(childName, data)` 
That would set the data as firebase would return it. 
Or you want the mock to be smart enough to order the data previously set for that child ?  
IMHO I'd suggest to make the Mock as dumb as posible, and I'd prefer to have the auxiliary method to set the content that call should return.  

I'm just starting to use this library, so I'm sorry if I'm question doesn't make sense.

**Comment by posva** [comment]
I wanted it to emit the corresponding events, which can be very complex as @soumak77 pointed out.
I think it depends on what you're using the mock for. I was using it to test some firebase plugins but in an application it makes more sense to simply mock the whole data

**Comment by soumak77** [comment]
Spies should be used to handle any complex ordering logic you need to test.  I've created a [tutorial for how to use spies](https://github.com/soumak77/firebase-mock/blob/master/tutorials/spies.md) to mock the orderBy* methods.
