### ISSUE TITLE
Add equalTo behavior

### ISSUE THREAD

**Issue by esprehn** [soumak77/firebase-mock#64]
This was supported by firebase-admin-mock which was deprecated in favor of this library.

https://github.com/sebasgarcep/firebase-admin-mock/blob/42bd3d862e28004ae97a7eed35b622843ccde05a/lib/database-accesors.js#L48

It should be easy to implement if you already have startAt/endAt since it's the same as setting the range endpoints to the same value. No reason to use spies there.

This is all the real firebase SDK does as well:
https://github.com/firebase/firebase-js-sdk/blob/73a586c92afe3f39a844b2be86086fddb6877bb7/packages/database/src/api/Query.ts#L565

@sebasgarcep

**Comment by soumak77** [comment]
Although the docs mention that these methods are not implemented due to their complex nature, I'm fine adding basic functionality for most use cases.  If someone needs more complex ordering, they can choose to use spies instead.

**Comment by sebasgarcep** [comment]
@soumak77 I invite you to reconsider your position on spies and complex ordering. A mocking library should attempt to replicate what it is mocking as closely as possible, even complicated under-the-hood stuff. If this is not on your roadmap please announce it clearly, so that we can keep `firebase-admin-mock` open to people who might need this alternative.

I really hope you reconsider, though. I strongly believe that splintered communities lead to inferior products. This should not be the case.

Best of luck!

**Comment by soumak77** [comment]
@sebasgarcep I am perfectly fine with this library mocking the behavior of the realtime database query methods.  The original reason this was not implemented was simply to not give people false hope that it would work for every use case.  I'm fine adding basic functionality, I'm just not sure whether or not it is possible to 100% mock the firebase logic without some bugs.   If it is possible and people can help test to verify that would be great.

**Comment by sebasgarcep** [comment]
@soumak77 Thanks for clarifying!

And there is hope! Firebase has documentation on how a lot of these things work under-the-hood. We already have a working and tested implementation down at `firebase-admin-mock` which is missing only priorities (I think). Maybe that can help. 😄 I wish I could put some man-hours into it, but I'm really busy right now 😭 .

**Comment by soumak77** [comment]
Anyone in the community want to work on getting this working?
